# Generated by Django 5.2.5 on 2025-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "__first__"),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="patronymic",
        ),
        migrations.AddField(
            model_name="doctor",
            name="clinics",
            field=models.ManyToManyField(
                related_name="doctors",
                to="clinic.clinic",
                verbose_name="Клиники, в которых работает доктор",
            ),
        ),
    ]
