# Generated by Django 5.2.5 on 2025-08-11 15:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0002_remove_doctor_first_name_remove_doctor_last_name_and_more"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Время начала консультации"),
                ),
                (
                    "end_time",
                    models.DateTimeField(verbose_name="Время конца консультации"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидает"),
                            ("confirmed", "Подтверждена"),
                            ("started", "Начата"),
                            ("completed", "Завершена"),
                            ("paid", "Оплачена"),
                        ],
                        default="waiting",
                        max_length=9,
                        verbose_name="Статус консультации",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        verbose_name="Результат консультации/Описание болезни или диагноза",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="doctor.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультация",
                "verbose_name_plural": "Консультации",
                "ordering": ("created_at",),
            },
        ),
    ]
