# Generated by Django 5.2.5 on 2025-08-11 11:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название клиники"),
                ),
                ("legal_address", models.TextField(verbose_name="Юридический адрес")),
                ("physical_address", models.TextField(verbose_name="Физический адрес")),
            ],
            options={
                "verbose_name": "Клиника",
                "verbose_name_plural": "Клиники",
                "ordering": ("created_at",),
            },
        ),
    ]
