# Generated by Django 5.2.5 on 2025-08-11 14:52

import uuid

import django.utils.timezone
import django_lifecycle.mixins
import phonenumber_field.modelfields
from django.db import migrations, models

import apps.helpers.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(default="", max_length=40, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(default="", max_length=40, verbose_name="Фамилия"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Пример, +79510549236",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="",
                        max_length=254,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superuser", "Суперпользователь"),
                            ("doctor", "Доктор"),
                            ("patient", "Пациент"),
                        ],
                        default="patient",
                        max_length=9,
                        verbose_name="Роль пользователя системы",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("email",),
                "abstract": False,
                "swappable": "AUTH_USER_MODEL",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                (
                    "objects",
                    apps.helpers.managers.CustomFieldUserManager(
                        username_field_name="phone"
                    ),
                ),
            ],
        ),
    ]
